# Generated by Django 2.2.2 on 2019-06-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='taken',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
