# Generated by Django 2.2.2 on 2019-06-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='nutrition',
            name='lunch',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='icon',
            field=models.CharField(default='breakfast', max_length=16),
            preserve_default=False,
        ),
    ]
